server:
  port: 8088
  servlet:
    context-path: /chatbot

spring:
  application:
    name: chatbot-service

  datasource:
    url: "jdbc:mysql://localhost:3306/chatbot_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: bachdau

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123456

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

        memory:
          repository:
            jdbc:
              initialize-schema: always

    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: products_vector
